let obj={
            head:{
                data:10,
                next:{
                    data:20,
                    next:{
                        data:30,
                        next:{
                            data:40,
                            next:{
                                data:50,
                                next:{
                                    data:60,
                                    next:{
                                        data:70,
                                        next:{
                                            data:80,
                                            next:null
                                            }
                                        }
                                    }
                                }
                            } 
                        }
                    }
               }
        }
        let x=obj.head
    while(x!=null)
    {
        console.log(x.data)        
        x=x.next
    }